SELECT 
	TOP (?)
	B.BLOG_ID,
	B.BLOG_NAME,
	CONCAT(
		'{',
		CONCAT('DATA',' : ', COALESCE(B.BLOG_CONTENT, '""')),
		'}'
	) AS BLOG_CONTENT,	
	B.IMAGE_URL,
	BT.ICON_CLASS,
	BT.BLOG_TYPE_NAME,
	CONVERT(VARCHAR(10), B.PUBLISHED_DATE, 34) AS PUBLISHED_DATE
FROM BLOG B
	JOIN BLOG_TYPE BT ON B.BLOG_TYPE_ID = BT.BLOG_TYPE_ID
WHERE B.DELETE_FLAG = 0
	AND B.ACTIVE_FLAG = 1
	AND B.USER_ID = ?
	AND BT.DELETE_FLAG = 0
	AND BT.ACTIVE_FLAG = 1
ORDER BY
	B.PUBLISHED_DATE DESC,
	COALESCE(B.UPDATED_DATE_TIME, B.CREATED_DATE_TIME) DESC